# Generated by cucumber-sinatra. (2014-11-13 20:25:46 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/toy_combination.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ToyCombination

class ToyCombinationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ToyCombinationWorld.new
end
