# Taken from the cucumber-rails project.
# IMPORTANT: This file is generated by cucumber-sinatra - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-sinatra. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))

Given(/^a user$/) do
  @session = ToyCombination.new
end

When(/^I visit the homepage$/) do
  visit('/')
end

Then(/^I should see an unshuffled toy$/) do
  expect(page).to have_content?('bunny_head.JPG')
end

Given(/^an unshuffled homepage$/) do
  pending # express the regexp above with the code you wish you had
end

When(/^I press the shuffle button$/) do
  pending # express the regexp above with the code you wish you had
end

Then(/^I should see a shuffled combination of toys$/) do
  pending # express the regexp above with the code you wish you had
end